language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g swagger-cli
  - npm install -g openapi-to-postmanv2
script:
  - npm run build
  - npm run postman
  - npm test
